name: Test schematic API

on:
  pull_request_review:
    types: [submitted, edited]
  workflow_dispatch:
    inputs:
      perform_benchmarking:
        required: true
        type: boolean
        default: False
        description: perform benchmarking test (True) or skip (False)



concurrency:
  # cancel the current running workflow from the same branch, PR when a new workflow is triggered
  # when the trigger is not a PR but a push, it will use the commit sha to generate the concurrency group
  # {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
  # {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag
  # {{ github.event.pull_request.number}}: get PR number
  # {{ github.sha }}: full commit sha
  # credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION:  1.2.0
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:

      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run API tests + Exclude Benchmarks
        if: ${{ false == inputs.perform_benchmarking }}
        run: echo "this seems okay"
